export const BREED_SUGGESTIONS = [
  "Quarter Horse",
  "Thoroughbred",
  "Paint",
  "Appaloosa",
  "Arabian",
  "Warmblood",
  "Friesian",
  "Morgan",
  "Tennessee Walking Horse",
  "Andalusian",
  "Draft Horse",
  "Mustang",
  "Standardbred",
  "Paso Fino",
  "Rocky Mountain Horse",
] as const;

export const DISCIPLINE_OTHER = "Other" as const;

export const DISCIPLINE_SUGGESTIONS = [
  "Barrel Racing",
  "Pole Bending",
  "Mounted Shooting",
  "Gymkhana",
  "Reining",
  "Cutting",
  "Team Roping",
  "Tie-Down Roping",
  "Breakaway Roping",
  "Working Cow Horse",
  "Ranch Sorting",
  "Team Penning",
  "Western Pleasure",
  "Ranch Riding",
  "Western Trail",
  "Rodeo",
  "Dressage",
  "Show Jumping",
  "Hunter/Hunter Under Saddle",
  "Eventing",
  "Halter/Conformation Showing",
  "Endurance Riding",
  "Driving",
  "Racing",
  "Pleasure Riding",
  "Polo",
  "Broodmare",
  "Retired",
] as const;

export const DISCIPLINE_SUGGESTIONS_WITH_OTHER = [
  ...DISCIPLINE_SUGGESTIONS,
  DISCIPLINE_OTHER,
] as const;
