export const BREED_SUGGESTIONS = [
  "Quarter Horse",
  "Thoroughbred",
  "Paint",
  "Appaloosa",
  "Arabian",
  "Warmblood",
  "Friesian",
  "Morgan",
  "Tennessee Walking Horse",
  "Andalusian",
  "Draft Horse",
  "Mustang",
  "Standardbred",
  "Paso Fino",
  "Rocky Mountain Horse",
] as const;

export const DISCIPLINE_SUGGESTIONS = [
  "Barrel Racing",
  "Reining",
  "Cutting",
  "Roping",
  "Team Penning",
  "Sorting",
  "Dressage",
  "Hunter/Jumper",
  "Eventing",
  "Western Pleasure",
  "Trail",
  "Endurance",
  "Polo",
  "Racing",
  "Broodmare",
  "Retired",
  "Pleasure Riding",
] as const;
