"use client";

import { useRouter } from "next/navigation";

export default function DisclaimerPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-black text-zinc-100">
      <button
        type="button"
        onClick={() => {
          if (window.history.length > 1) {
            router.back();
          } else {
            router.push("/");
          }
        }}
        className="px-6 pt-6 text-sm font-medium text-accent transition hover:text-accent-hover"
      >
        ← Back
      </button>

      <main className="mx-auto max-w-2xl px-6 pb-16 pt-6">
        <h1 className="mb-6 text-2xl font-bold text-white">
          AI Analysis Disclaimer
        </h1>
        <p className="mb-4 leading-relaxed text-zinc-300">
          The conformation analysis and scores provided by EquiForm are
          generated by artificial intelligence and are intended for
          informational and educational purposes only. They do not
          constitute professional veterinary advice, diagnosis, or
          evaluation.
        </p>
        <p className="mb-4 leading-relaxed text-zinc-300">
          AI-generated scores and assessments reflect pattern recognition
          based on photo analysis and should not be used as the sole basis
          for breeding, purchasing, selling, training, or veterinary
          decisions. Individual horse conformation is complex and nuanced —
          factors including horse movement, temperament, soundness history,
          and physical examination by a qualified veterinarian or certified
          equine professional are essential to any complete evaluation.
        </p>
        <p className="mb-4 leading-relaxed text-zinc-300">
          EquiForm makes no warranty, express or implied, regarding the
          accuracy, completeness, or fitness for any particular purpose of
          the analysis provided. Results may vary based on photo quality,
          angle, lighting, and other factors outside EquiForm&apos;s
          control.
        </p>
        <p className="mb-4 leading-relaxed text-zinc-300">
          By using EquiForm, you agree that Hennis Performance Horses,
          ProgenXai LLC, and EquiForm&apos;s founders, employees, and agents
          are not liable for any decisions made based on AI-generated
          conformation scores or reports.
        </p>
      </main>
    </div>
  );
}
